site_name: Dengue Dashboard Docs
nav:
  - Home: 'index.md'
  - 'Getting Started':
    - 'Installation': '02_Installation.md'
    - 'Basics' :
      - 'General' : '03_basics.md'
      - 'Back end (Django)': '03_basics_backend.md'
      - 'Front end (Vue.js)': '03_basics_frontend.md'
  - 'Deeper dive':
    - 'Back End':
      - 'Project Structure': '04_backend.md'
      - 'Local development': '04_backend_local.md'
      - 'Production': '04_backend_production.md'
      - 'API Documentation': '04_backend_apidocs.md'
      - 'Django Admin': '04_backend_admin.md'
    - 'Front End':
        - 'Project Structure': '05_frontend.md'
        - 'Local development': '05_frontend_local.md'
        - 'Production': '05_frontend_production.md'
  - 'Tutorials':
    - 'Back End':
        - 'New REST API Endpoint': '00_tut_api.md'
        - 'New WebSocket Endpoint': '00_tut_ws.md'
        - 'Send messages via WebSocket to clients': '00_tut_ws_02.md'
    - 'Front End':
        - 'Create a new report': '00_tut_create.md'
        - 'Update a report': '00_tut_update.md'
        - 'Delete a report': '00_tut_delete.md'
        - 'Retrieve a list of reports': '00_tut_retrieve.md'
        - 'New Page': '00_tut_page.md'
        - 'Work with new data from the back end': '00_tut_actions.md'
  - 'FAQ' : '06_faq.md'
  - 'Resources' : '07_Resources.md'
  - 'Changelog' : 'Changelog.md'

theme:
  name: material
  logo: assets/SVG/logo.svg
  palette:
    - scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - search
markdown_extensions:
    - pymdownx.tabbed
    - pymdownx.superfences
    - attr_list
    - admonition
    - pymdownx.superfences
    - pymdownx.details
extra_css:
  - assets/termynal.css
  - assets/styling.css
extra_javascript:
  - assets/termynal.js
  - assets/custom.js