site_name: Dengue Dashboard Docs
nav:
  - Home: 'index.md'
  - 'Getting Started':
    - 'Installation': '02_Installation.md'
    - 'Basics' : '03_basics.md'
  - 'The System':
    - 'Back End': '04_backend.md'
    - 'Front End': '05_frontend.md'
  - 'Tutorials':
    - 'Back End':
        - 'New REST API Endpoint': '00_tut_api.md'
        - 'New WebSocket Endpoint': '00_tut_ws.md'
        - 'Send messages via WebSocket to clients': '00_tut_ws_02.md'
    - 'Front End':
        - 'Create a new report': '00_tut_create.md'
        - 'Update a report': '00_tut_update.md'
        - 'Delete a report': '00_tut_delete.md'
        - 'Retrieve a list of reports': '00_tut_retrieve.md'
        - 'New Page': '00_tut_page.md'
        - 'Work with new data from the back end': '00_tut_actions.md'
  - 'FAQ' : '06_faq.md'
  - 'Resources' : '07_Resources.md'
  - 'Changelog' : 'Changelog.md'

theme:
  name: material
  logo: assets/SVG/logo.svg
  palette:
    - scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - search
markdown_extensions:
    - pymdownx.tabbed
    - pymdownx.superfences
    - attr_list
    - admonition
    - pymdownx.superfences
    - pymdownx.details
extra_css:
  - assets/termynal.css
extra_javascript:
  - assets/termynal.js
  - assets/custom.js