site_name: Dengue Dashboard Docs
theme:
  name: material
  logo: assets/SVG/logo.svg
plugins:
  - search
markdown_extensions:
    - pymdownx.tabbed
    - pymdownx.superfences
    - attr_list
    - admonition
    - pymdownx.superfences
    - pymdownx.details